### ISSUE TITLE
Can Protobuf be removed from server so any usb ccid reader can connect to server 

### ISSUE THREAD

**Issue by WearOS-NFC** [nfcgate/server#4]
@kleest 
Can protobuf be removed from server so any usb ccid reader can connect to server from pc without any software acting as client to relay pcsc apdu to nfcgate ?

Thanks

**Comment by kleest** [comment]
No, protobuf is required for server <-> client and client <-> client communication. You can of course write your own client that encapsulates APDUs in NFCGate protocol messages.
