### ISSUE TITLE
Error ( 00 6D 00) on APDUs

### ISSUE THREAD

**Issue by Barladulos** [nfcgate/server#6]
I'm sorry for the trouble, I want to mention that I managed to make the application, I installed the server properly with the protobuf library and python3 already installed. I mention that the phones are connected to each other, but when I want to do a test, it cannot process the transaction, telling me that the instruction is invalid.
I encountered that error before, but by updating the new protobuf I managed to make it functional.
What can i do ? 
Now I have the newest version of protobuf, I also tried with the 2.6.1.
Need to try 3.x version of protobuf?
Thank you for your help and i apreciated you guys for all your work.

Congratulations for all of you!![Screenshot 2024-02-03 165653](https://github.com/nfcgate/server/assets/158513568/fc239c9f-a340-418d-8775-771dfff194fa)

**Comment by roussosalex** [comment]
Hello, I unfortunately do not understand this issue. Where exactly does the error `00 6D 00` come from? How does it relate to protobuf? The server requires at least protobuf version 3, but newer versions should be compatible as well.

**Comment by roussosalex** [comment]
Since the error is on APDU Level and the messages seem to be consistent, I don't think the issue has anything to do with protobuf. Maybe your last protobuf update only "accidentally" fixed the issue? Could the reader be rejecting the card due to transaction time or an issue with the NFC chip? Could you post some details about the devices you are using (e.g. screenshot of the status page, how they are connected, where the server is running in terms of network)?

**Comment by Barladulos** [comment]
First of all I want to thank you for the previous answer.
As can be seen in the screenshots, everything is correct from a technical point of view.
The server used is set accordingly according to the NFCGate parameters.
The server is running from the point of view of the network in Lithuania.
I must mention the fact that there are no improper settings in the server.
Thank you for your assistance and answers.
There are no problems related to the time of the transaction, at the same time that the time zone and local time of the server are set accordingly.
![Screenshot 2024-02-08 114222](https://github.com/nfcgate/server/assets/158513568/dd695370-826f-4dd8-bb39-eabc91415e9f)
